#!/bin/bash

set -e

# could potentially be a branch
backup_dir=`mktemp -d -p $PWD`

tmp_dirs=`ls tmp.* | xargs`
ignore_files="README.md dotfiles .git $tmp_dirs" 

# to come...
sym_dir='bin'

function main {
  list_dot_files |
  prefix_dot |
  backup_files

  list_dot_files |
  symlink_files
}

function prefix_dot {
  while read file; do
    echo .$file
  done
}

function backup_files {
  while read file; do
    mv $HOME/$file $backup_dir/$file
  done
}

function symlink_files {
  while read file; do
    ln -s $PWD/$file $HOME/.$file
  done
}

function list_dot_files {
  for file in `ls`; do
    grep -vq $file <(echo $ignore_files $sym_dir) && echo $file
  done
}

main
